update-dep: rm .net logic related to removed metadata
I noticed that dependency-builds of dotnet sdk, runtime etc are failing
to update buildpacks (e.g.
https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/jobs/update-dotnet-sdk-6.0.x-dotnet-core/builds/16)

Intercepting the containers, error shows
`run.rb:345:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)`

Looks like field `runtime_to_sdks` was removed in https://github.com/cloudfoundry/dotnet-core-buildpack/pull/734